[package]
name = "rpm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
flate2 = "1.1.2"
reqwest = { version = "0.12.22",features = ["blocking"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4.44"

